# docker run -e MYSQL_ROOT_PASSWORD=gokstad -d mysql:latest

FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=gokstad

# IKKE nødvending å ha med, men best practice å spesifisere porten som brukes
EXPOSE 3306