services:
  db:
    image: yngvemag/ga-mysql-db:2026
    # platform: linux/arm64 # MAC M1/M2 uncomment this line
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    container_name: ga-mysql-db-phpmyadmin
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 23456:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: gokstad
    depends_on:
      - db
    
volumes:
  db-data: